name: my-node-pipeline

on:
  push:
    branches: [main]

jobs:
  Setup-and-deploy:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      
     # - name: Installing Dependencies
      #  run: npm install

      #- name: Run the app
       # run: pm2 start npm --name "my-node-pipeline" -- start -- -p 3000
       
      - name: Building the Docker image
        run: |
         sudo docker build . -t my-node-pipeline
         sudo docker image ls

      - name: running the Docker image
        run: |
         sudo docker container run -dit -p 3000:3000 my-node-pipeline /bin/bash
